%macro shrink(nam);
    data _null_;
    call symput('dir',pathname(scan("&nam",1,'.')));
    call symput('dset',scan("&nam",2,'.'));
    run;
    filename com pipe "gzip &dir./&dset..sas7bdat";
    data _null_;
    infile com firstobs=1 length=linelen;
    input var $1. @ ;
    input @1 errstat $varying200. linelen;
    errstat='ERROR: '||errstat;
    put errstat=;
    run;
%mend shrink;
